#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.SMSWebServices
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SMS")]
	public partial class SMSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertShift_Staff(Shift_Staff instance);
    partial void UpdateShift_Staff(Shift_Staff instance);
    partial void DeleteShift_Staff(Shift_Staff instance);
    partial void InsertShift_Master(Shift_Master instance);
    partial void UpdateShift_Master(Shift_Master instance);
    partial void DeleteShift_Master(Shift_Master instance);
    partial void InsertUserInformation(UserInformation instance);
    partial void UpdateUserInformation(UserInformation instance);
    partial void DeleteUserInformation(UserInformation instance);
    #endregion
		
		public SMSDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SMSConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SMSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SMSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SMSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SMSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Shift_Staff> Shift_Staffs
		{
			get
			{
				return this.GetTable<Shift_Staff>();
			}
		}
		
		public System.Data.Linq.Table<Shift_Master> Shift_Masters
		{
			get
			{
				return this.GetTable<Shift_Master>();
			}
		}
		
		public System.Data.Linq.Table<UserInformation> UserInformations
		{
			get
			{
				return this.GetTable<UserInformation>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Shift_Staff")]
	public partial class Shift_Staff : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Shift_ID;
		
		private string _Staff_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnShift_IDChanging(string value);
    partial void OnShift_IDChanged();
    partial void OnStaff_IDChanging(string value);
    partial void OnStaff_IDChanged();
    #endregion
		
		public Shift_Staff()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shift_ID", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Shift_ID
		{
			get
			{
				return this._Shift_ID;
			}
			set
			{
				if ((this._Shift_ID != value))
				{
					this.OnShift_IDChanging(value);
					this.SendPropertyChanging();
					this._Shift_ID = value;
					this.SendPropertyChanged("Shift_ID");
					this.OnShift_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Staff_ID", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Staff_ID
		{
			get
			{
				return this._Staff_ID;
			}
			set
			{
				if ((this._Staff_ID != value))
				{
					this.OnStaff_IDChanging(value);
					this.SendPropertyChanging();
					this._Staff_ID = value;
					this.SendPropertyChanged("Staff_ID");
					this.OnStaff_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Shift_Master")]
	public partial class Shift_Master : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _shift_ID;
		
		private string _shiftdep;
		
		private System.Nullable<System.DateTime> _ShiftDateFrom;
		
		private System.Nullable<System.DateTime> _ShiftDateTo;
		
		private string _ShiftTimeFrom;
		
		private string _ShiftTimeTo;
		
		private string _Location;
		
		private string _superid;
		
		private string _supername;
		
		private string _supercontno;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onshift_IDChanging(string value);
    partial void Onshift_IDChanged();
    partial void OnshiftdepChanging(string value);
    partial void OnshiftdepChanged();
    partial void OnShiftDateFromChanging(System.Nullable<System.DateTime> value);
    partial void OnShiftDateFromChanged();
    partial void OnShiftDateToChanging(System.Nullable<System.DateTime> value);
    partial void OnShiftDateToChanged();
    partial void OnShiftTimeFromChanging(string value);
    partial void OnShiftTimeFromChanged();
    partial void OnShiftTimeToChanging(string value);
    partial void OnShiftTimeToChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnsuperidChanging(string value);
    partial void OnsuperidChanged();
    partial void OnsupernameChanging(string value);
    partial void OnsupernameChanged();
    partial void OnsupercontnoChanging(string value);
    partial void OnsupercontnoChanged();
    #endregion
		
		public Shift_Master()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shift_ID", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string shift_ID
		{
			get
			{
				return this._shift_ID;
			}
			set
			{
				if ((this._shift_ID != value))
				{
					this.Onshift_IDChanging(value);
					this.SendPropertyChanging();
					this._shift_ID = value;
					this.SendPropertyChanged("shift_ID");
					this.Onshift_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shiftdep", DbType="VarChar(15)")]
		public string shiftdep
		{
			get
			{
				return this._shiftdep;
			}
			set
			{
				if ((this._shiftdep != value))
				{
					this.OnshiftdepChanging(value);
					this.SendPropertyChanging();
					this._shiftdep = value;
					this.SendPropertyChanged("shiftdep");
					this.OnshiftdepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShiftDateFrom", DbType="DateTime")]
		public System.Nullable<System.DateTime> ShiftDateFrom
		{
			get
			{
				return this._ShiftDateFrom;
			}
			set
			{
				if ((this._ShiftDateFrom != value))
				{
					this.OnShiftDateFromChanging(value);
					this.SendPropertyChanging();
					this._ShiftDateFrom = value;
					this.SendPropertyChanged("ShiftDateFrom");
					this.OnShiftDateFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShiftDateTo", DbType="DateTime")]
		public System.Nullable<System.DateTime> ShiftDateTo
		{
			get
			{
				return this._ShiftDateTo;
			}
			set
			{
				if ((this._ShiftDateTo != value))
				{
					this.OnShiftDateToChanging(value);
					this.SendPropertyChanging();
					this._ShiftDateTo = value;
					this.SendPropertyChanged("ShiftDateTo");
					this.OnShiftDateToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShiftTimeFrom", DbType="VarChar(30)")]
		public string ShiftTimeFrom
		{
			get
			{
				return this._ShiftTimeFrom;
			}
			set
			{
				if ((this._ShiftTimeFrom != value))
				{
					this.OnShiftTimeFromChanging(value);
					this.SendPropertyChanging();
					this._ShiftTimeFrom = value;
					this.SendPropertyChanged("ShiftTimeFrom");
					this.OnShiftTimeFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShiftTimeTo", DbType="VarChar(30)")]
		public string ShiftTimeTo
		{
			get
			{
				return this._ShiftTimeTo;
			}
			set
			{
				if ((this._ShiftTimeTo != value))
				{
					this.OnShiftTimeToChanging(value);
					this.SendPropertyChanging();
					this._ShiftTimeTo = value;
					this.SendPropertyChanged("ShiftTimeTo");
					this.OnShiftTimeToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(25)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_superid", DbType="VarChar(30)")]
		public string superid
		{
			get
			{
				return this._superid;
			}
			set
			{
				if ((this._superid != value))
				{
					this.OnsuperidChanging(value);
					this.SendPropertyChanging();
					this._superid = value;
					this.SendPropertyChanged("superid");
					this.OnsuperidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_supername", DbType="VarChar(30)")]
		public string supername
		{
			get
			{
				return this._supername;
			}
			set
			{
				if ((this._supername != value))
				{
					this.OnsupernameChanging(value);
					this.SendPropertyChanging();
					this._supername = value;
					this.SendPropertyChanged("supername");
					this.OnsupernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_supercontno", DbType="VarChar(20)")]
		public string supercontno
		{
			get
			{
				return this._supercontno;
			}
			set
			{
				if ((this._supercontno != value))
				{
					this.OnsupercontnoChanging(value);
					this.SendPropertyChanging();
					this._supercontno = value;
					this.SendPropertyChanged("supercontno");
					this.OnsupercontnoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserInformation")]
	public partial class UserInformation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserID;
		
		private string _UserPassword;
		
		private string _FirstName;
		
		private string _MiddleName;
		
		private string _LastName;
		
		private string _KinName;
		
		private string _HomeAddress;
		
		private string _City;
		
		private string _State;
		
		private string _Country;
		
		private string _Mobile;
		
		private string _Phone;
		
		private string _Fax;
		
		private string _EmailId;
		
		private string _PostalCode;
		
		private string _KinContactNo;
		
		private string _NRICno;
		
		private System.Nullable<System.DateTime> _DOB;
		
		private string _Role;
		
		private string _Staff_ID;
		
		private string _UserSecretQues;
		
		private string _UserSecretAns;
		
		private string _UserStatus;
		
		private System.Nullable<System.DateTime> _LastLoginTime;
		
		private System.Nullable<System.DateTime> _LastActivityTime;
		
		private string _ImagePathName;
		
		private string _ManagementRole;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnUserPasswordChanging(string value);
    partial void OnUserPasswordChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnKinNameChanging(string value);
    partial void OnKinNameChanged();
    partial void OnHomeAddressChanging(string value);
    partial void OnHomeAddressChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnMobileChanging(string value);
    partial void OnMobileChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnEmailIdChanging(string value);
    partial void OnEmailIdChanged();
    partial void OnPostalCodeChanging(string value);
    partial void OnPostalCodeChanged();
    partial void OnKinContactNoChanging(string value);
    partial void OnKinContactNoChanged();
    partial void OnNRICnoChanging(string value);
    partial void OnNRICnoChanged();
    partial void OnDOBChanging(System.Nullable<System.DateTime> value);
    partial void OnDOBChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    partial void OnStaff_IDChanging(string value);
    partial void OnStaff_IDChanged();
    partial void OnUserSecretQuesChanging(string value);
    partial void OnUserSecretQuesChanged();
    partial void OnUserSecretAnsChanging(string value);
    partial void OnUserSecretAnsChanged();
    partial void OnUserStatusChanging(string value);
    partial void OnUserStatusChanged();
    partial void OnLastLoginTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnLastLoginTimeChanged();
    partial void OnLastActivityTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnLastActivityTimeChanged();
    partial void OnImagePathNameChanging(string value);
    partial void OnImagePathNameChanged();
    partial void OnManagementRoleChanging(string value);
    partial void OnManagementRoleChanged();
    #endregion
		
		public UserInformation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserPassword", DbType="VarChar(30)")]
		public string UserPassword
		{
			get
			{
				return this._UserPassword;
			}
			set
			{
				if ((this._UserPassword != value))
				{
					this.OnUserPasswordChanging(value);
					this.SendPropertyChanging();
					this._UserPassword = value;
					this.SendPropertyChanged("UserPassword");
					this.OnUserPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(30)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="VarChar(30)")]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this.OnMiddleNameChanging(value);
					this.SendPropertyChanging();
					this._MiddleName = value;
					this.SendPropertyChanged("MiddleName");
					this.OnMiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(30)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KinName", DbType="VarChar(30)")]
		public string KinName
		{
			get
			{
				return this._KinName;
			}
			set
			{
				if ((this._KinName != value))
				{
					this.OnKinNameChanging(value);
					this.SendPropertyChanging();
					this._KinName = value;
					this.SendPropertyChanged("KinName");
					this.OnKinNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomeAddress", DbType="VarChar(60)")]
		public string HomeAddress
		{
			get
			{
				return this._HomeAddress;
			}
			set
			{
				if ((this._HomeAddress != value))
				{
					this.OnHomeAddressChanging(value);
					this.SendPropertyChanging();
					this._HomeAddress = value;
					this.SendPropertyChanged("HomeAddress");
					this.OnHomeAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(20)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(20)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(30)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="VarChar(20)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this.OnMobileChanging(value);
					this.SendPropertyChanging();
					this._Mobile = value;
					this.SendPropertyChanged("Mobile");
					this.OnMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(30)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(20)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailId", DbType="VarChar(50)")]
		public string EmailId
		{
			get
			{
				return this._EmailId;
			}
			set
			{
				if ((this._EmailId != value))
				{
					this.OnEmailIdChanging(value);
					this.SendPropertyChanging();
					this._EmailId = value;
					this.SendPropertyChanged("EmailId");
					this.OnEmailIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostalCode", DbType="VarChar(30)")]
		public string PostalCode
		{
			get
			{
				return this._PostalCode;
			}
			set
			{
				if ((this._PostalCode != value))
				{
					this.OnPostalCodeChanging(value);
					this.SendPropertyChanging();
					this._PostalCode = value;
					this.SendPropertyChanged("PostalCode");
					this.OnPostalCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KinContactNo", DbType="VarChar(30)")]
		public string KinContactNo
		{
			get
			{
				return this._KinContactNo;
			}
			set
			{
				if ((this._KinContactNo != value))
				{
					this.OnKinContactNoChanging(value);
					this.SendPropertyChanging();
					this._KinContactNo = value;
					this.SendPropertyChanged("KinContactNo");
					this.OnKinContactNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRICno", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NRICno
		{
			get
			{
				return this._NRICno;
			}
			set
			{
				if ((this._NRICno != value))
				{
					this.OnNRICnoChanging(value);
					this.SendPropertyChanging();
					this._NRICno = value;
					this.SendPropertyChanged("NRICno");
					this.OnNRICnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="DateTime")]
		public System.Nullable<System.DateTime> DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="VarChar(30)")]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Staff_ID", DbType="VarChar(30)")]
		public string Staff_ID
		{
			get
			{
				return this._Staff_ID;
			}
			set
			{
				if ((this._Staff_ID != value))
				{
					this.OnStaff_IDChanging(value);
					this.SendPropertyChanging();
					this._Staff_ID = value;
					this.SendPropertyChanged("Staff_ID");
					this.OnStaff_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserSecretQues", DbType="VarChar(50)")]
		public string UserSecretQues
		{
			get
			{
				return this._UserSecretQues;
			}
			set
			{
				if ((this._UserSecretQues != value))
				{
					this.OnUserSecretQuesChanging(value);
					this.SendPropertyChanging();
					this._UserSecretQues = value;
					this.SendPropertyChanged("UserSecretQues");
					this.OnUserSecretQuesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserSecretAns", DbType="VarChar(20)")]
		public string UserSecretAns
		{
			get
			{
				return this._UserSecretAns;
			}
			set
			{
				if ((this._UserSecretAns != value))
				{
					this.OnUserSecretAnsChanging(value);
					this.SendPropertyChanging();
					this._UserSecretAns = value;
					this.SendPropertyChanged("UserSecretAns");
					this.OnUserSecretAnsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserStatus", DbType="VarChar(30)")]
		public string UserStatus
		{
			get
			{
				return this._UserStatus;
			}
			set
			{
				if ((this._UserStatus != value))
				{
					this.OnUserStatusChanging(value);
					this.SendPropertyChanging();
					this._UserStatus = value;
					this.SendPropertyChanged("UserStatus");
					this.OnUserStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLoginTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastLoginTime
		{
			get
			{
				return this._LastLoginTime;
			}
			set
			{
				if ((this._LastLoginTime != value))
				{
					this.OnLastLoginTimeChanging(value);
					this.SendPropertyChanging();
					this._LastLoginTime = value;
					this.SendPropertyChanged("LastLoginTime");
					this.OnLastLoginTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastActivityTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastActivityTime
		{
			get
			{
				return this._LastActivityTime;
			}
			set
			{
				if ((this._LastActivityTime != value))
				{
					this.OnLastActivityTimeChanging(value);
					this.SendPropertyChanging();
					this._LastActivityTime = value;
					this.SendPropertyChanged("LastActivityTime");
					this.OnLastActivityTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagePathName", DbType="VarChar(100)")]
		public string ImagePathName
		{
			get
			{
				return this._ImagePathName;
			}
			set
			{
				if ((this._ImagePathName != value))
				{
					this.OnImagePathNameChanging(value);
					this.SendPropertyChanging();
					this._ImagePathName = value;
					this.SendPropertyChanged("ImagePathName");
					this.OnImagePathNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagementRole", DbType="VarChar(35)")]
		public string ManagementRole
		{
			get
			{
				return this._ManagementRole;
			}
			set
			{
				if ((this._ManagementRole != value))
				{
					this.OnManagementRoleChanging(value);
					this.SendPropertyChanging();
					this._ManagementRole = value;
					this.SendPropertyChanged("ManagementRole");
					this.OnManagementRoleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
